"""production_sync

Revision ID: fb5d7dca1541
Revises: 0006_security_admin_report_compat
Create Date: 2026-08-10 17:40:53.368325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5d7dca1541'
down_revision: Union[str, None] = '0006_security_admin_report_compat'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_collection_post', 'collection_items', ['collection_id', 'post_id'])
    op.create_unique_constraint('unique_collection_reel', 'collection_items', ['collection_id', 'reel_id'])
    op.drop_index(op.f('idx_creator_wallet_user'), table_name='creator_wallets')
    op.drop_index(op.f('idx_deleted_message_user'), table_name='deleted_messages')
    op.alter_column('messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.alter_column('music', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_music_use_count'), table_name='music')
    op.create_foreign_key(None, 'music', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reel_comments', 'reel_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reels', 'music', ['music_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'reels', ['reel_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'stories', ['story_id'], ['id'], ondelete='SET NULL')
    op.add_column('saved_collections', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_saved_collection_user'), table_name='saved_collections')
    op.drop_index(op.f('idx_user_online_status_user'), table_name='user_online_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_online_status_user'), 'user_online_status', ['user_id'], unique=1)
    op.create_index(op.f('idx_saved_collection_user'), 'saved_collections', ['user_id'], unique=False)
    op.drop_column('saved_collections', 'updated_at')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reels', type_='foreignkey')
    op.drop_constraint(None, 'reel_comments', type_='foreignkey')
    op.drop_constraint(None, 'music', type_='foreignkey')
    op.create_index(op.f('ix_music_use_count'), 'music', ['use_count'], unique=False)
    op.alter_column('music', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.alter_column('messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('idx_deleted_message_user'), 'deleted_messages', ['user_id'], unique=False)
    op.create_index(op.f('idx_creator_wallet_user'), 'creator_wallets', ['user_id'], unique=1)
    op.drop_constraint('unique_collection_reel', 'collection_items', type_='unique')
    op.drop_constraint('unique_collection_post', 'collection_items', type_='unique')
    # ### end Alembic commands ###
